<a href="https://colab.research.google.com/github/henrygas/unsupervised_learning/blob/master/tfidf_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 装载Google云盘

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


## 2. 定位当前工作目录

In [0]:
# !ls drive/My\ Drive/app/tfidf_test
import os
os.chdir("./drive/My Drive/app/tfidf_test")

In [15]:
!ls

data  out


## 3. 学习词袋模型CountVectorizer

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
vec.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [17]:
corpos = [
          "This is the first document.",
          "This is the second second document.",
          "And the third one.",
          "Is this the first document?"
]
X = vec.fit_transform(corpos)
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [18]:
vec.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [19]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [20]:
# 词汇表
vec.vocabulary_

{'and': 0,
 'document': 1,
 'first': 2,
 'is': 3,
 'one': 4,
 'second': 5,
 'the': 6,
 'third': 7,
 'this': 8}

针对其他文本进行词袋处理时，可以直接使用现有的词汇表

In [0]:
vec_new = CountVectorizer(vocabulary=vec.vocabulary_)

在将来的fit_transform()方法中，在词汇表vocabulary_中未出现的词将被完全忽略。

In [22]:
vec_new.fit_transform(["Something third new."]).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0]])

第二个例子，增加出现文档频率的要求

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

vec_df = CountVectorizer(min_df=3, ngram_range=(1, 1))
content=np.array([
    '<s[NULL]cript>alert(1)</s[NULL]cript>X</a>',
    '\'><video><source o?UTF-8?Q?n?error="alert(1)">',
    '\'><FRAMESET><FRAME RC=""+"javascript:alert(\'X\');"></FRAMESET>',
    '"></script>\'//<svg "%0Aonload=alert(1) //>',
    '"></script><img \'//"%0Aonerror=alert(1)// src>',
    'id%3Den%22%3E%3Cscript%3Ealert%28%22AKINCILAR%22%29%3C/script%3E',
    '?a%5B%5D%3D%22%3E%3Cscript%3Ealert%28document.cookie%29%3C/script%3E',
    '><iframe src="data:data:javascript:,% 3 c script % 3 e confirm(1) % 3 c/script %3 e">',
    '?mess%3D%3Cscript%3Ealert%28document.cookie%29%3C/script%3E%26back%3Dsettings1',
    'title%3D%3Cscript%3Ealert%28%22The%20Best%20XSSer%22%29%3C/script%3E',
    '<script charset>alert(1);</script charset>',
    '"><meta charset="x-mac-farsi">??script ??alert(1)//??/script ??',
    '</script><script>/*"/*\'/**/;alert(1)//</script>#',
])

X_2 = vec_df.fit_transform(content)
vec_df.get_feature_names()

['22', '29', '3c', '3cscript', '3d', '3e', '3ealert', 'alert', 'script']

In [27]:
X_2

<13x9 sparse matrix of type '<class 'numpy.int64'>'
	with 44 stored elements in Compressed Sparse Row format>

In [28]:
X_2.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1],
       [2, 1, 1, 1, 0, 2, 1, 0, 1],
       [1, 1, 1, 1, 1, 2, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 2],
       [0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 1, 3]])

In [29]:
vec_df.vocabulary_

{'22': 0,
 '29': 1,
 '3c': 2,
 '3cscript': 3,
 '3d': 4,
 '3e': 5,
 '3ealert': 6,
 'alert': 7,
 'script': 8}

## 4. 学习TF-IDF

是一种加权技术，是词频(TF)和逆文档频率(IDF)的乘积
+ 在一个文档中高频出现，但在其他文档中很少出现的词，最能反映当前文档的特色，于是这样的词，就被施以高权重；
+ 在所有文档中都高频出现，意味着TF高，但IDF低，这样的词，大多属于无意义的常用词，就被施以低权重；
+ 从上面的分析可以看出，文档数越多，IDF的影响越大，结果也越公正；如果只有一篇文档，那么TF就和TF-IDF相同了，这样就不能看出高频出现的词，到底是有意义的专业词，还是无意义的常用词了。

简单理解: 一个人，假设他对所有人都很好，那他对你的好，就不那么醒目了；如果他对其他所有人都很苛刻，但对你还不错，那么你就知道，他是真的对你好了

但这个模型，有以下三个缺陷，下面举例说明:

(1) 第一个缺陷，比如一个人，他可能对水瓶座的人很有好感，于是他对遇到的所有水瓶，都很好，那如果你参考的样本里，恰好大部分都是水瓶，那他对你的好，就被忽略了，因为不够醒目嘛，但实际上，喜欢水瓶恰恰是他的一个性质

(2) 第二个缺陷，就是没考虑这个人当时的处境；因为你观察到了结果(喜欢/不喜欢)，而忽略了他产生这个结果时的实时处境，所以你也做出了误判

(3) 第三个缺陷，他可能只是恰好对你的某个特质感兴趣，并不是真的喜欢你这个人，但你通过观测结果，也无法分析出这个结论

这就是TF-IDF的三大缺陷：
+ 没有考虑到特征项在类间和类内的分布情况;
+ 没有考虑特征项的位置因素对文本的区分度;
+ 会对一些无意义的生僻字施以高权重，但并不能提高对文本的区分度

In [0]:
content = [
    "I went to your house and steal your rice to eat, but bitten by your dog, so I think you need to pay me.",
    "I thought to play with you this afternoon, however it will rain later, so you have to play with yourself.",
    "I decided to make friends with you when I saw your wife first sight."
]

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform(content).toarray()

In [50]:
X_tfidf.shape

(3, 38)

In [51]:
X_tfidf

array([[0.        , 0.20729109, 0.20729109, 0.20729109, 0.20729109,
        0.        , 0.20729109, 0.20729109, 0.        , 0.        ,
        0.        , 0.20729109, 0.        , 0.        , 0.        ,
        0.        , 0.20729109, 0.20729109, 0.20729109, 0.        ,
        0.        , 0.20729109, 0.        , 0.        , 0.15765022,
        0.20729109, 0.20729109, 0.        , 0.        , 0.36728838,
        0.20729109, 0.        , 0.        , 0.        , 0.        ,
        0.12242946, 0.47295066, 0.        ],
       [0.22540243, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.22540243, 0.        , 0.22540243, 0.22540243, 0.22540243,
        0.        , 0.        , 0.        , 0.        , 0.45080485,
        0.22540243, 0.        , 0.        , 0.        , 0.17142435,
        0.        , 0.        , 0.22540243, 0.22540243, 0.26625261,
        0.        , 0.        , 0.        , 0.22540243, 0.34284871,
   

## 5. TF-IDF和词袋的配合使用

前面我们看出，TF-IDF的作用是找出某些词用以提取该词所在文档的特色，而词袋模型的作用是找出文档中出现频率高的词；

而有特色的词，既有可能是有意义的专业词，又有可能是无意义的生僻词，可以考虑将两者结合起来，具体步骤是:

+ 通过词袋模型挑出一堆热词;
+ 再用TF-IDF对这些热词加权，得到有区分度的词。


这样就可以通过控制热词数，来将无意义的常用词和有意义的专业词都框进来；

然后再通过加权技术，排除掉无意义的常用词，争取留下有意义的专业词。

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

content=np.array([
    '<s[NULL]cript>alert(1)</s[NULL]cript>X</a>',
    '\'><video><source o?UTF-8?Q?n?error="alert(1)">',
    '\'><FRAMESET><FRAME RC="" "javascript:alert(\'X\');"></FRAMESET>',
    '"></script>\'//<svg "onload=alert(1) //>',
    '"></script><img \'//"onerror=alert(1)// src>',
    'id=en"><script>alert("AKINCILAR")</script>',
    '?a[]="><script>alert(document.cookie)</script>',
    '><iframe src="data:data:javascript:,% 3 c script % 3 e confirm(1) % 3 c/script %3 e">',
    '?mess=<script>alert(document.cookie)</script>&back=settings1',
    'title=<script>alert("The Best XSSer")</script>',
    '<script charset>alert(1);</script charset>',
    '"><meta charset="x-mac-farsi">??script ??alert(1)//??/script ??',
    '</script><script>/*"/*\'/**/;alert(1)//</script>#',
])

count_vec = CountVectorizer()
X_count = count_vec.fit_transform(content)

tfidf_transform = TfidfTransformer()
X_tfidf = tfidf_transform.fit_transform(X_count)

In [72]:
import pandas as pd

df = pd.DataFrame(data=X_tfidf.toarray(), columns=count_vec.get_feature_names())
df

akincilar     alert      back  ...       utf     video     xsser
0    0.000000  0.127851  0.000000  ...  0.000000  0.000000  0.000000
1    0.000000  0.179349  0.000000  ...  0.491893  0.491893  0.000000
2    0.000000  0.139040  0.000000  ...  0.000000  0.000000  0.000000
3    0.000000  0.239872  0.000000  ...  0.000000  0.000000  0.000000
4    0.000000  0.208634  0.000000  ...  0.000000  0.000000  0.000000
5    0.510113  0.185992  0.000000  ...  0.000000  0.000000  0.000000
6    0.000000  0.238848  0.000000  ...  0.000000  0.000000  0.000000
7    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
8    0.000000  0.157925  0.433135  ...  0.000000  0.000000  0.000000
9    0.000000  0.165681  0.000000  ...  0.000000  0.000000  0.454406
10   0.000000  0.186608  0.000000  ...  0.000000  0.000000  0.000000
11   0.000000  0.170248  0.000000  ...  0.000000  0.000000  0.000000
12   0.000000  0.277167  0.000000  ...  0.000000  0.000000  0.000000

[13 rows x 36 columns]

tf-idf值越高区分语句的效果越好；

但tf-idf值越高，泛化能力越差；

选择特征向量时，应该选择泛化能力强，即tf-idf值较低的。

在这个例子里：
+ alert的权重普遍比较低，但它的泛化能力较好；
+ script的权重也比较低，有一定的泛化能力，但相比alert还是略差一点。
+ 其他的词，往往在个别的单个文档中出现，权值虽高，但不具有泛化能力，不应该作为特征向量。